# Generated by Django 5.0.9 on 2024-10-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_is_patient_user_is_pharmacist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=True),
        ),
    ]
