# Generated by Django 5.0.9 on 2024-11-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
    ]
